FROM python:3.8.12

RUN pip3 install cython pysam BioUtil
RUN pip3 install biopython
RUN pip3 install numpy

COPY cluster.py /cluster.py

LABEL org.opencontainers.image.source=https://github.com/cyclomics/cycloseq