FROM ubuntu:21.04

RUN apt-get update && apt-get -y upgrade && apt-get install -y build-essential zlib1g-dev wget && \
        apt-get clean && apt-get purge && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /usr/src
RUN wget https://github.com/weizhongli/cdhit/releases/download/V4.8.1/cd-hit-v4.8.1-2019-0228.tar.gz && \
	tar xfz cd-hit-v4.8.1-2019-0228.tar.gz && \
	rm cd-hit-v4.8.1-2019-0228.tar.gz && \
	cd cd-hit-v4.8.1-2019-0228 && \
	make && \
	cd cd-hit-auxtools && \
	make

ENV PATH=${PATH}:/usr/src/cd-hit-v4.8.1-2019-0228:/usr/src/cd-hit-v4.8.1-2019-0228/cd-hit-auxtools

RUN wget https://github.com/yangao07/abPOA/releases/download/v1.2.5/abPOA-v1.2.5.tar.gz
RUN tar -zxvf abPOA-v1.2.5.tar.gz && cd 
WORKDIR /usr/src/abPOA-v1.2.5
RUN make
ENV PATH=${PATH}:/usr/src/abPOA-v1.2.5/bin/
WORKDIR /