FROM centos:8.4.2105
LABEL org.opencontainers.image.source=https://github.com/cyclomics/cycloseq

RUN dnf install wget make gcc gcc-c++ zlib-devel -y

RUN wget https://github.com/yangao07/TideHunter/releases/download/v1.5.3/TideHunter-v1.5.3.tar.gz
RUN tar -zxf TideHunter-v1.5.3.tar.gz 
WORKDIR /TideHunter-v1.5.3
RUN make
# add all the spelling cases
RUN ln -s /TideHunter-v1.5.3/bin/TideHunter /bin/tidehunter
RUN ln -s /TideHunter-v1.5.3/bin/TideHunter /bin/Tidehunter
RUN ln -s /TideHunter-v1.5.3/bin/TideHunter /bin/TideHunter

