FROM centos:8.4.2105

RUN dnf install wget make gcc gcc-c++ zlib-devel -y

RUN wget https://github.com/yangao07/TideHunter/releases/download/v1.5.2/TideHunter-v1.5.2.tar.gz
RUN tar -zxf TideHunter-v1.5.2.tar.gz 
WORKDIR /TideHunter-v1.5.2
RUN make
# add all the spelling cases
RUN ln -s /TideHunter-v1.5.2/bin/TideHunter /bin/tidehunter
RUN ln -s /TideHunter-v1.5.2/bin/TideHunter /bin/Tidehunter
RUN ln -s /TideHunter-v1.5.2/bin/TideHunter /bin/TideHunter

