FROM centos:8.4.2105

RUN dnf install git python2 python3 python3-devel gcc zlib make zlib-devel unzip make automake gcc gcc-c++ kernel-devel -y

# py2 and py are used to install pbdagcon
RUN ln -s /usr/bin/python2 /usr/bin/python
RUN pip3 install Cython
# COPY . /app
# RUN pip3 install -r /app/requirements.txt

#### PBDAGCON INSTALL ####
ENV blasr_matrix_file=/pbdagcon/blasr_libcpp/pbdata/matrix/FlatMatrix.hpp


RUN git clone https://github.com/PacificBiosciences/pbdagcon.git
WORKDIR /pbdagcon
RUN mkdir -p /pbdagcon/src/third-party/boost
RUN curl -L https://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz | tar -zxf - && \
    mv boost_1_58_0/boost /pbdagcon/src/cpp/third-party/boost_1_58_0-headersonly
RUN cp -r /pbdagcon/src/cpp/third-party/boost_1_58_0-headersonly /pbdagcon/src/cpp/third-party/boost


# run the python script to make it make buildable
RUN python ./configure.py --boost --gtest --sub --no-pbbam
# We let make init fail, but we f ixthe neccecery files that we fix later
RUN make init-submodule ; exit 0
RUN sed -i '6 i #include <iostream>' ${blasr_matrix_file}
# Then, fetch and build the relevant portions of the blasr_libcpp submodule
RUN make init-submodule

# build pbdagcon executable (Makefile fetches boost headers)
RUN make ; exit 0
RUN sed -i '18 i #define DAZZ_DB HITS_DB' /pbdagcon/src/cpp/DazAlnProvider.hpp
RUN make

# syslink te resulting executables
RUN ln -s /pbdagcon/src/cpp/pbdagcon /usr/bin/pbdagcon
RUN ln -s /pbdagcon/src/cpp/dazcon /usr/bin/dazcon
