FROM python:3.6.2

RUN apt update
RUN apt install -y build-essential python3-dev

RUN pip3 install Cython setuptools_scm
RUN pip3 install --user whatshap

RUN apt install samtools

RUN git clone https://github.com/vibansal/HapCUT2.git
WORKDIR /HapCUT2
RUN make

WORKDIR /
RUN ln -s $HOME/.local/bin/whatshap /bin/whatshap