name: Unittests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:  
  RunPythonUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cycas
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}  # activate the conda environment
        run: |
          conda info
          python -m unittest
          conda list
