name: Unittests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:  
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t my-python-app .

      # Step 4: Run the Docker container and execute tests
      - name: Run tests in Docker container
        run: docker run my-python-app python -m unittest
