FROM python:3.6.2

RUN pip3 install cython pysam BioUtil 

RUN git clone https://github.com/sein-tao/bam2m5.git
WORKDIR /bam2m5
RUN sed -i 's/from pysam.calignmentfile cimport AlignmentFile, AlignedSegment/from pysam.libcalignmentfile cimport AlignmentFile, AlignedSegment/1' cbam2m5.pyx
RUN python3 cython_build.py

RUN pip3 install bioconvert