# This is a basic workflow to help you get started with Actions

name: docker building

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # login to Github container registry (GHCR)
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DR_PAT_GHCR }}
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: build_dockers
        run: |
          echo $$GITHUB_SHA
          for i in $(ls docker); do
            echo $i
            docker build docker/$i -t ghcr.io/cyclomics/$i:${GITHUB_REF#refs/heads/}-$(git rev-parse --short "$GITHUB_SHA")
            docker tag ghcr.io/cyclomics/$i:${GITHUB_REF#refs/heads/}-$(git rev-parse --short "$GITHUB_SHA") ghcr.io/cyclomics/$i:latest
            docker push ghcr.io/cyclomics/$i:${GITHUB_REF#refs/heads/}-$(git rev-parse --short "$GITHUB_SHA")
            docker push ghcr.io/cyclomics/$i:latest
          done


