# This is a basic workflow to help you get started with Actions

name: docker building

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: build_dockers
        run: |
          for i in $(ls docker); do
            echo $i
            echo docker build docker/$i -t cyclomics/$i:$GITHUB_REF 
          done
      - name: parameters
        run: |
          echo $(git rev-parse --short "$GITHUB_SHA")
          echo ${GITHUB_REF#refs/heads/}

