# This is a basic workflow to help you get started with Actions

name: docker building

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , dev ]
  pull_request:
    branches: [ main , dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DR_PAT_GHCR }}
        
      - name: build_dockers
        run: |
          echo $GITHUB_RUN_ID
          echo "Building $(ls docker)"
          for i in $(ls docker); do
            echo $i
            echo docker build docker/$i -t ghcr.io/cyclomics/$i:GITHUB_RUN_ID
            docker build docker/$i -t ghcr.io/cyclomics/$i:GITHUB_RUN_ID
            docker tag ghcr.io/cyclomics/$i:GITHUB_RUN_ID ghcr.io/cyclomics/$i:latest
            docker push ghcr.io/cyclomics/$i:GITHUB_RUN_ID
            docker push ghcr.io/cyclomics/$i:latest
          done

  test_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - name: Run Nextflow pipeline
        run: |
          nextflow run informed.nf \
          --input_read_dir 'tests/informed'\
          --read_pattern '/fastq_pass/*.fastq' \
          --backbone_fasta 'tests/informed/backbone_test.fa' \
          --backbone_name BB_fake \
          --reference 'tests/informed/tp53.fasta' \
          --ci_run
