# This is a basic workflow to help you get started with Actions

name: Pipeline execution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , dev ]
  pull_request:
    branches: [ main , dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  RunPipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - name: Run Nextflow pipeline
        run: |
          nextflow run main.nf \
          --input_read_dir 'tests/informed' \
          --read_pattern '/fastq_pass/*.fastq' \
          --backbone_fasta 'tests/informed/backbone_test.fa' \
          --reference 'tests/informed/tp53.fasta' \
          --ci_run 

  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: create conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cyclomics-nf-cyclomicseq
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Run tests with pytest
        run: python -m unittest 